### ISSUE TITLE
Two improve suggestions

### ISSUE THREAD

**Issue by skyao** [aleen42/gitbook-treeview#2]
Thank you for this great plugin, this is just I want :) 

Yet I still have two suggestions:
1. Can we close or don't display the line of "copyright"? For example, add a simple logic, check if copyright is set to empty (like "copyright": "") then we don't display this line.
2. For some small pages, the content is short, it won't require a treeview. So can we add two configure parameters: { "minHeaderCount": 5, "minHeaderDeep": 3} , so the only when count of header is greater than 5 or deep of header is greater than 3 that we will generate the treeview.

Then I think this plugin is more suitable to use.

**Comment by aleen42** [comment]
Well, I see. Thanks for your suggestions, and I'm a little busy recently. Would you mind directly making a change above my code, and giving a pull request? If do, I will change it for you soon or later.

**Comment by aleen42** [comment]
Just wait for a moment, I will release one new version for this issue.

**Comment by aleen42** [comment]
@skyao Hello, check the latest **version 2.6.5**!!
